<!-- ==================Title================== -->
<title><?php Util::to_print($context->getTitle()); ?></title>

<!-- ==================Metatags================== -->
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<meta name="language" content="germany" />
<meta name="author" content="mboehm" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<meta name="keywords" CONTENT="<?php Util::to_print(IConsts::META_KEYWORDS); ?>" />
<meta name="description" CONTENT="<?php Util::to_print(IConsts::META_DESCRIPTION); ?>" />

<!-- ==================Stylesheets================== -->
<link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="<?php echo CSS_B ?>bootstrap.css" type="text/css" />
<link rel="stylesheet" href="<?php echo BASE ?>style.css" type="text/css" />
<link rel="stylesheet" href="<?php echo CSS_B ?>dark.css" type="text/css" />
<link rel="stylesheet" href="<?php echo CSS_B ?>font-icons.css" type="text/css" />
<link rel="stylesheet" href="<?php echo CSS_B ?>animate.css" type="text/css" />
<link rel="stylesheet" href="<?php echo CSS_B ?>magnific-popup.css" type="text/css" />
<link rel="stylesheet" href="<?php echo CSS_B ?>responsive.css" type="text/css" />
<link rel="stylesheet" href="<?php echo CSS ?>main.css" type="text/css" />

<!-- ==================JavaScripts================== -->
<script type="text/javascript" src="<?php echo JS_B ?>jquery.js"></script>
<script type="text/javascript" src="<?php echo JS_B ?>plugins.js"></script>
