<!-- ==================GoTopButton================== -->
<div id="gotoTop" class="icon-angle-up"></div>

<!-- ==================JavaScripts================== -->
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="<?php echo JS_B ?>jquery.gmap.js"></script>
<script type="text/javascript" src="<?php echo JS_B ?>functions.js"></script>
<script type="text/javascript" src="<?php echo JS ?>swipperSlider.js"></script>
<script type="text/javascript" src="<?php echo JS ?>main.js"></script>