<section id="slider" class="slider-parallax swiper_wrapper full-screen clearfix background-banner">
    <div class="container clearfix">
        <div class="vertical-middle dark spacing-banner-text">
            <div class="heading-block nobottommargin">
                <h1>
                    <span class="text-rotater nocolor" data-separator="|" data-rotate="flipInX" data-speed="3500">
                        Ihr<span class="t-rotate">e||</span> 
                        <span class="t-rotate rotate-color">
                            <?php $html->out(IConsts::SLIDER_TEXT_ROTATE); ?>
                        </span> 
                        <?php $html->out("in Professionellen Händen"); ?>                        
                    </span>
                </h1> 
<!--                <span class="hidden-xs">Learn how to grow your Awesome idea into a successful business.</span>-->
            </div>
        </div>
    </div>
</section>