<?php

require_once CLASSES . 'utils/IConsts.class.php';
require_once CLASSES . 'utils/Util.class.php';
require_once CLASSES . 'utils/Sessions.class.php';
require_once CLASSES . 'database/DB.class.php';
require_once CLASSES . 'application/ApplicationContextManager.class.php';
require_once CLASSES . 'application/ApplicationContextModel.class.php';
require_once CLASSES . 'application/ApplicationContextDB.class.php';
require_once CLASSES . 'application/sections/AbstractSection.class.php';
require_once CLASSES . 'application/sections/TeamSection.class.php';
require_once CLASSES . 'application/sections/ServiceSection.class.php';
require_once CLASSES . 'application/navigation/NavigationModel.class.php';
require_once CLASSES . 'application/navigation/NavigationService.class.php';
require_once CLASSES . 'HTMLElementsBuilder.class.php';
require_once CLASSES . 'admin/AdministrationManager.class.php';
require_once CLASSES . 'admin/AdministrationDB.class.php';
require_once 'base/include/phpmailer/class.phpmailer.php';
require_once CLASSES . 'MessageMail.class.php';
?>