<!-- ==================Section About================== -->
<?php include INC_PATH . 'index_about.inc'; ?>
<!-- ==================Section Team================== -->
<?php include INC_PATH . 'index_team.inc'; ?>
<!-- ==================Section Services================== -->
<?php include INC_PATH . 'index_service.inc'; ?>
<!-- ==================Section Contact================== -->
<?php include INC_PATH . 'index_contact.inc'; ?>









